apiVersion: v1
kind: Service              
metadata:
 name: flask-helloworld-lb
spec:
 type: LoadBalancer       
 ports:
 - port: 5000               
   protocol: TCP          
   targetPort: 5000
   #nodePort: 30000        
 selector:                
   app: flask-helloworld      